version: '3.8'

networks:
  development:
    driver: bridge

volumes:
  cassandra-data:

services:

  # Responsible for coordination and synchronization between distributed systems, such as Kafka and HBase.
  zookeeper:
    image: ubuntu/zookeeper:3.8-22.04_edge
    container_name: zookeeper
    networks:
      - development
    mem_limit: 512M
    cpus: 0.25

  # Provides a web-based user interface for monitoring and managing Zookeeper clusters.
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    networks:
      - development
    ports:
      - "${ZOONAVIGATOR_UI_PORT}:9000"
    environment:
      HTTP_PORT: 9000
      CONNECTION_LOCALZK_NAME: "Local ZooKeeper"
      CONNECTION_LOCALZK_CONN: "zookeeper:2181"
    depends_on:
      - zookeeper
    mem_limit: 512M
    cpus: 0.25

 # A distributed streaming platform used for real-time data ingestion and processing.
  kafka:
    image: ubuntu/kafka:3.6-22.04_edge
    container_name: kafka
    networks:
      - development
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - ./kafka-server.properties:/etc/kafka/server.properties
    depends_on:
      - zookeeper
    mem_limit: 512M
    cpus: 0.5

  # Offers a user interface for monitoring Kafka clusters and topics.
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    networks:
      - development
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: default
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    mem_limit: 512M
    cpus: 0.5

  # Offers real time stream processing
  flink-jobmanager:
    build:
      context: .
      dockerfile: flinkDockerfile
    container_name: flink-jobmanager
    networks:
      - development
    ports:
      - "${FLINK_UI_PORT}:8081"
      - "${FLINK_RPC_PORT_JOBMANAGER}:6123"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    mem_limit: 512M
    cpus: 0.5

  flink-taskmanager:
    build:
      context: .
      dockerfile: flinkDockerfile
    container_name: flink-taskmanager
    networks:
      - development
    command: taskmanager
    ports:
      - "${FLINK_RPC_PORT_TASKMANAGER}:6122"
      - "${FLINK_DATA_PORT_TASKMANAGER}:6121"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - flink-jobmanager
    mem_limit: 512M
    cpus: 0.5


  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - '${CASSANDRA_PORT}:9042'
    volumes:
      - cassandra-data:/bitnami/cassandra
#      - ./init_cassandra.sh:/docker-entrypoint-initdb.d/init_cassandra.sh
#    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init_cassandra.sh"]
    mem_limit: 384M
    cpus: 0.25
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=64M
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_ENABLE_AUTH=no
      - ALLOW_EMPTY_PASSWORD=yes