apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: CASSANDRA_ENABLE_AUTH
              value: "no"
            - name: CASSANDRA_PASSWORD
              value: cassandra
            - name: CASSANDRA_USERNAME
              value: cassandra
            - name: HEAP_NEWSIZE
              value: 512M
            - name: MAX_HEAP_SIZE
              value: 512M
          image: bitnami/cassandra:latest
          name: cassandra
          ports:
            - containerPort: 9042
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /home
              name: cassandra-data
      hostname: cassandra
      restartPolicy: Always
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-data
