apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: flink-jobmanager
  name: flink-jobmanager
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "6123"
      port: 6123
      targetPort: 6123
  selector:
    io.kompose.service: flink-jobmanager
